name: 堡垒机官方镜像转存

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 登陆阿里云镜像仓库
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-wulanchabu.aliyuncs.com
      - name: 拉取堡垒机官方镜像重命名后推送到阿里云个人仓库
        run: |
          version=v4.0.2
          docker pull jumpserver/jms_core:${version}
          docker pull jumpserver/jms_koko:${version}
          docker pull jumpserver/guacd:1.5.5-bookworm
          docker pull jumpserver/jms_lion:${version}
          docker pull jumpserver/jms_chen:${version}
          docker pull jumpserver/jms_web:${version}

          docker tag jumpserver/jms_core:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_core:${version}
          docker tag jumpserver/jms_koko:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_koko:${version}
          docker tag jumpserver/guacd:1.5.5-bookworm registry.cn-wulanchabu.aliyuncs.com/marbleqi/guacd:1.5.5-bookworm
          docker tag jumpserver/jms_lion:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_lion:${version}
          docker tag jumpserver/jms_chen:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_chen:${version}
          docker tag jumpserver/jms_web:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_web:${version}

          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_core:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_koko:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/guacd:1.5.5-bookworm
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_lion:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_chen:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_web:${version}
