name: 制作镜像并推送到私有仓库

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 登陆阿里云镜像仓库
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-wulanchabu.aliyuncs.com
      - name: 拉取堡垒机相关镜像并推送到阿里云个人仓库
        run: |
          version=v4.0.0
          docker pull jumpserver/jms_core:${version}
          docker pull jumpserver/jms_koko:${version}
          docker pull jumpserver/jms_lion:${version}
          docker pull jumpserver/jms_chen:${version}
          docker pull jumpserver/jms_web:${version}

          docker tag jumpserver/jms_core:${version} registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_core:${version}
          docker tag jumpserver/jms_koko:${version} registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_koko:${version}
          docker tag jumpserver/jms_lion:${version} registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_lion:${version}
          docker tag jumpserver/jms_chen:${version} registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_chen:${version}
          docker tag jumpserver/jms_web:${version} registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_web:${version}

          docker push registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_core:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_koko:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_lion:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_chen:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/${DOCKER_USERNAME}/jms_web:${version}
