name: 堡垒机官方镜像转存

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 登陆阿里云镜像仓库
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-wulanchabu.aliyuncs.com
      - name: 拉取堡垒机官方镜像重命名后推送到阿里云个人仓库
        run: |
          version=v4.2.0
          docker pull jumpserver/jms_all:${version}

          docker tag jumpserver/jms_all:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_all:${version}

          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms_all:${version}
