name: 堡垒机官方镜像转存

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/jumpserver.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 登陆阿里云镜像仓库
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-wulanchabu.aliyuncs.com
      - name: 拉取堡垒机官方镜像重命名后推送到阿里云个人仓库
        run: |
          version=v4.3.0-ce

          docker pull jumpserver/core:${version}
          docker pull jumpserver/koko:${version}
          docker pull jumpserver/lion:${version}
          docker pull jumpserver/chen:${version}
          docker pull jumpserver/web:${version}

          docker tag jumpserver/core:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-core:${version}
          docker tag jumpserver/koko:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-koko:${version}
          docker tag jumpserver/lion:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-lion:${version}
          docker tag jumpserver/chen:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-chen:${version}
          docker tag jumpserver/web:${version} registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-web:${version}

          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-core:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-koko:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-lion:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-chen:${version}
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/jms-web:${version}
