name: node官方镜像转存

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/node.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 登陆阿里云镜像仓库
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-wulanchabu.aliyuncs.com
      - name: 拉取node官方镜像重命名后推送到阿里云个人仓库
        run: |
          docker pull node:16
          docker pull node:18
          docker pull node:20

          docker tag node:16 registry.cn-wulanchabu.aliyuncs.com/marbleqi/node:16
          docker tag node:18 registry.cn-wulanchabu.aliyuncs.com/marbleqi/node:18
          docker tag node:20 registry.cn-wulanchabu.aliyuncs.com/marbleqi/node:20

          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/node:16
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/node:18
          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/node:20
