name: opensearch官方镜像转存

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/opensearch.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 登陆阿里云镜像仓库
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD registry.cn-wulanchabu.aliyuncs.com
      - name: 拉取mysql官方镜像重命名后推送到阿里云个人仓库
        run: |
          docker pull opensearchproject/opensearch:1.3.19

          docker tag opensearchproject/opensearch:1.3.19 registry.cn-wulanchabu.aliyuncs.com/marbleqi/opensearch:1.3.19

          docker push registry.cn-wulanchabu.aliyuncs.com/marbleqi/opensearch:1.3.19













